version: "3"

services:
  users:
    container_name: demo-project-users
    build:
      context: ../
      dockerfile: ./docker/backend/users/Dockerfile
    ports:
      - "8090:3000"
    environment:
      PORT: 3000
    depends_on:
      - db
    volumes:
      - ../backend/services/users:/usr/src/app
    # networks:
    #   - esnet
  products:
    container_name: demo-project-products
    build:
      context: ../
      dockerfile: ./docker/backend/products/Dockerfile
    ports:
      - "8091:3000"
    environment:
      PORT: 3000
    depends_on:
      - db
    volumes:
      - ../backend/services/products:/usr/src/app
    # networks:
    #   - esnet
  db:
    container_name: demo-project-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    # volumes:
    #   - ./data_db:/var/lib/mysql
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "projects"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "1"
    ports: 
      - "3307:3306"   
  nginx:
    container_name: demo-project-nginx
    image: nginx:alpine
    ports:
      - "81:80"
    volumes:
      - ./nginx/public:/srv/www/static
      - ../docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - users
      - products
      - db
    # networks:
    #   - esnet

volumes:
  esdata:
    driver: local
# networks:
#   esnet:
